@startuml
'''classes
class Lampe{
-nom : String
-allume : boolean
+Lampe(String)
+allumer() : void
+eteindre() : void
+toString() : String
+isAllume() : boolean
+equals() : boolean
}
class Hifi{
-son : int
+allumer() : void
+eteindre() : void
+toString() : String
}
'''relations
Telecommande "*" --> "*"Lampe : -lampes
Telecommande "*" --> "*"Hifi : -hifis
@enduml