@startuml
'''classes
class Lampe{
-nom : String
-allume : boolean
+Lampe(String)
+allumer() : void
+éteindre() : void
+toString() : String
+isAllume() : boolean
+equals() : boolean
}
'''relations
@enduml