@startuml
'https://plantuml.com/sequence-diagram

class Lampe{
-nom : String
-allume : boolean
+Lampe(String)
+allumer() : void
+eteindre() : void
+toString() : String
+isAllume() : boolean
+equals() : boolean
}

class Telecommande{
+ Telecommande()
+ activerTout()
+ ajouterTelecommandable(Telecommandable)
+ allumer(int)
+ eteindre(int)
+ toString(): String
}

class Hifi{
-son : int
+Hifi()
+allumer() : void
+eteindre() : void
+toString() : String
}

class Television{
-son : int
-allume : boolean
+Television()
+allumer() : void
+eteindre() : void
+augmenterVolume() : void
+diminuerVolume() : void
+toString() : String
}

Interface Telecommandable{
 + allumer(): void
 + eteindre() : void
}


class Cheminee{
    + intensite: int
    +Cheminee() : void
    + changerIntensite(int):void
    + getLumiere():int
}

class TelecommandeSpeciale{

}

'''relations
Telecommande "1" -> "*"Telecommandable: -telecommandables
Hifi  .up.|> Telecommandable
Television .up.|> Telecommandable
Lampe .up.|> Telecommandable
TelecommandeSpeciale ..|> Telecommandable
TelecommandeSpeciale "*" --> "*" Cheminee : -cheminees
@endum