@startuml
'https://plantuml.com/sequence-diagram

class Lampe{
-nom : String
-allume : boolean
+Lampe(String)
+allumer() : void
+eteindre() : void
+toString() : String
+isAllume() : boolean
+equals() : boolean
}

class Telecommande{
+ Telecommande()
+ activerTout()
+ ajouterTelecommandable(Telecommandable)
+ allumer(int)
+ eteindre(int)
+ toString(): String
}

class Hifi{
-son : int
+Hifi()
+allumer() : void
+eteindre() : void
+toString() : String
}

class Television{
-son : int
-allume : boolean
+Television()
+allumer() : void
+eteindre() : void
+augmenterVolume() : void
+diminuerVolume() : void
+toString() : String
}

'''relations
Telecommande "1" --> "*"Lampe: -lampes
Telecommande "1" --> "*"Hifi: -hifis
Telecommande "1" --> "0.1"Television: -televisions



@enduml